export const CURRENCY_SYMBOL_SUCCESS = 'CURRENCY_SYMBOL_SUCCESS';
export const CURRENCY_SYMBOL_ERROR = 'CURRENCY_SYMBOL_ERROR';

export const CURRENCY_RATES_SUCCESS = 'CURRENCY_RATES_SUCCESS';
export const CURRENCY_RATES_ERROR = 'CURRENCY_RATES_ERROR';

export const CHANGE_BASE = 'CHANGE_BASE';
